image: node:10.16.0 # can be upgraded, depending on your node version used

pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - npm run deploy
  artifacts:
    paths:
    - public # mandatory, other folder won't work
  only:
  - master # or dev, the branch you want to publish